Repository bitcrowd/bitstyles, pull requests merged in 2022-02, with the labels that each got.

#614 Update workflow name and badges
  .github/workflows/run-checks.yml
  README.md
Labels: Documentation

#617 Fix broken font-license link
  README.md
Labels: Documentation

#615 [#612] Update atoms/content documentation
  scss/bitstyles/atoms/avatar/avatar.stories.mdx
  scss/bitstyles/atoms/badge/_badge.scss
  scss/bitstyles/atoms/badge/badge.stories.mdx
  scss/bitstyles/atoms/bordered-header/bordered-header.stories.mdx
  scss/bitstyles/atoms/card/card.stories.mdx
  scss/bitstyles/atoms/content/content.stories.mdx
  scss/bitstyles/atoms/dl/dl.stories.mdx
  scss/bitstyles/atoms/dropdown/dropdown.stories.mdx
  scss/bitstyles/atoms/flash/flash.stories.mdx
  scss/bitstyles/atoms/icon/icon.stories.mdx
  scss/bitstyles/atoms/link/link.stories.mdx
  scss/bitstyles/atoms/topbar/topbar.stories.mdx
  scss/bitstyles/ui/icons.stories.mdx
  test/scss/fixtures/bitstyles-overrides.css
  test/scss/fixtures/bitstyles.css
Labels: Documentation

#616 [#603] Cleanup some outdated references in docs
  CHANGELOG.md
  scss/bitstyles/atoms/card/card.stories.mdx
  scss/bitstyles/tools/_size.scss
  scss/bitstyles/tools/_zindex.scss
  scss/bitstyles/utilities/font/_font.scss
  scss/bitstyles/utilities/margin/margin.stories.mdx
  scss/bitstyles/utilities/padding/padding.stories.mdx
Labels: Documentation

#592 [#588] allow sidebar organism to change sides
  CHANGELOG.md
  scss/bitstyles/organisms/sidebar/_settings.scss
  scss/bitstyles/organisms/sidebar/_sidebar.scss
  scss/bitstyles/ui/sidebar.stories.mdx
  test/scss/fixtures/bitstyles-overrides.css
  test/scss/test-import-all.scss
  test/scss/test-import-each.scss
  test/scss/test-use-all.scss
  test/scss/test-use-each.scss
Labels: Sass/CSS

#619 [#613] Add docs: design tokens
  scss/bitstyles/settings/animation.stories.mdx
  scss/bitstyles/settings/breakpoints.stories.mdx
  scss/bitstyles/settings/color-palette.stories.mdx
  scss/bitstyles/settings/shadows.stories.mdx
  scss/bitstyles/settings/sizes.stories.mdx
  scss/bitstyles/settings/typography.stories.mdx
  scss/bitstyles/ui/Colors.stories.js
Labels: Documentation

#631 Update dependencies 2022-02-12
  .eslintrc.json
  .storybook/main.js
  package.json
  test/css-stats.json
  test/scss/fixtures/bitstyles-overrides.css
  test/scss/fixtures/bitstyles.css
  yarn.lock
Labels: Infrastructure

#625 [#487] Add customisation guides
  CHANGELOG.md
  package.json
  scss/bitstyles/settings/typography.stories.mdx
  scss/bitstyles/utilities/absolute-center/absolute-center.stories.mdx
  scss/bitstyles/utilities/aspect-ratio/aspect-ratio.stories.mdx
  scss/bitstyles/utilities/bg/bg.stories.mdx
  scss/bitstyles/utilities/border/border.stories.mdx
  scss/bitstyles/utilities/box-shadow/box-shadow.stories.mdx
  scss/bitstyles/utilities/col-span/col-span.stories.mdx
  scss/bitstyles/utilities/col-start/col-start.stories.mdx
  scss/bitstyles/utilities/display/display.stories.mdx
  scss/bitstyles/utilities/drop-shadow/drop-shadow.stories.mdx
  scss/bitstyles/utilities/fg/fg.stories.mdx
  scss/bitstyles/utilities/flex/flex.stories.mdx
  scss/bitstyles/utilities/font/font.stories.mdx
  scss/bitstyles/utilities/gap/gap.stories.mdx
  scss/bitstyles/utilities/grid-cols/grid-cols.stories.mdx
  scss/bitstyles/utilities/items/items.stories.mdx
  scss/bitstyles/utilities/justify/justify.stories.mdx
  scss/bitstyles/utilities/margin/margin.stories.mdx
  scss/bitstyles/utilities/overflow/overflow.stories.mdx
  scss/bitstyles/utilities/padding/_index.scss
  scss/bitstyles/utilities/padding/_settings.scss
  scss/bitstyles/utilities/padding/padding.stories.mdx
  scss/bitstyles/utilities/row-start/row-start.stories.mdx
  scss/bitstyles/utilities/self/self.stories.mdx
  scss/bitstyles/utilities/sr-only/sr-only.stories.mdx
  scss/bitstyles/utilities/text/text.stories.mdx
  scss/bitstyles/utilities/z-index/z-index.stories.mdx
  yarn.lock
Labels: Documentation

#627 [#488] Getting started docs
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/preview.js
  CONTRIBUTING.md
  README.md
  scss/bitstyles/ui/extending-bitstyles.stories.mdx
  scss/bitstyles/ui/getting-started.stories.mdx
  scss/bitstyles/ui/principles.stories.mdx
  scss/bitstyles/ui/ui-components.mdx
Labels: Built on another PR, Documentation

#632 [#599] Add utility: border-radius
  CHANGELOG.md
  scss/bitstyles.scss
  scss/bitstyles/organisms/ui-group/ui-group.stories.mdx
  scss/bitstyles/ui/app-layouts.stories.mdx
  scss/bitstyles/ui/filter.stories.mdx
  scss/bitstyles/ui/forms.stories.mdx
  scss/bitstyles/ui/joined-buttons.stories.mdx
  scss/bitstyles/utilities/border-radius/_index.import.scss
  scss/bitstyles/utilities/border-radius/_index.scss
  scss/bitstyles/utilities/border-radius/_settings.scss
  scss/bitstyles/utilities/border-radius/border-radius.stories.mdx
  scss/bitstyles/utilities/box-shadow/_index.scss
  scss/bitstyles/utilities/round/_index.scss
  scss/bitstyles/utilities/round/round.stories.mdx
  test/scss/fixtures/bitstyles-overrides.css
  test/scss/fixtures/bitstyles.css
  test/scss/test-import-all.scss
  test/scss/test-import-each.scss
  test/scss/test-use-all.scss
  test/scss/test-use-each.scss
Labels: Sass/CSS

#628 Unify NodeJS setup
  .nvmrc
  CONTRIBUTING.md
Labels: Infrastructure
